### ISSUE TITLE
Provide NodeJS Infrastructure via Devcontainer

### ISSUE THREAD

**Issue by jbeverid** [onehungrymind/fem-enterprise-patterns#9]
To make things easier to get the project up and running on a machine that already has a different version of NodeJS and not needing NVM on your local machine, the application should be placed in a devcontainer.

Here are a couple of files that could be added to make things easier:
**.gitattributes**
```
*.sh text eol=lf
```

**.devcontainer/.devcontainer.json**
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
{
  "name": "fem-enterprise-patterns",
  "dockerComposeFile": "docker-compose.yml",
  "service": "devcontainer",
  "workspaceFolder": "/fem-enterprise-patterns",
  "customizations": {
    "vscode": {
      "extensions": [
        "angular.ng-template",
        "ms-vscode.vscode-typescript-tslint-plugin",
        "esbenp.prettier-vscode",
        "firsttris.vscode-jest-runner",
        "streetsidesoftware.code-spell-checker",
      ]
    }
  },
  "features": {
  },
  "mounts": [
    "source=fem-enterprise-patterns-node_modules,target=${containerWorkspaceFolder}/node_modules,type=volume",
    "source=${localEnv:HOME}${localEnv:USERPROFILE}/.gitconfig,target=/home/node/.gitconfig,type=bind"

  ],
  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  "forwardPorts": [3100, 4200, 4300, 4400, 4500],
  "postCreateCommand": "yarn",
  "remoteEnv": {}
}
```

**.devcontainer/docker-compose.yml**
```
version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "12-bullseye"

    volumes:
      - ..:/fem-enterprise-patterns:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
```

**.devcontainer/Dockerfile**
```
# [Choice] NodeJS Version
ARG VARIANT=12-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:${VARIANT}

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=18
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# Copy the entry point script into the image
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

RUN mkdir -p /fem-enterprise-patterns/node_modules
RUN chown -R node:node /fem-enterprise-patterns/node_modules

# If you want to install more global node packages
RUN su node -c "npm install -g @angular/cli@^10.1.0"
```

**.devcontainer/entrypoint.sh**
```
#!/bin/bash

# ================================================
# IMPORTANT
# ================================================
# FILE MUST HAVE UNIX-STYLE EOL CHARACTERS (LF)!!!
# ================================================

# Set /fem-enterprise-patterns as a safe directory for Git
echo 'Setting /fem-enterprise-patterns to be a shared safe directory for git...'
git config --global --add safe.directory /fem-enterprise-patterns
git config --global core.autocrlf false
echo 'Successfully set /fem-enterprise-patterns to be a shared safe directory!'

# Set node_module permissions
echo 'Creating node_modules (if does not exist) and fixing permissions...'
mkdir -p /fem-enterprise-patterns/node_modules
chown -R node:node /fem-enterprise-patterns/node_modules
echo 'Successfully configured node_modules!'

# Execute the Docker command
exec "$@"
```

Finally, from tthe `.vscode/extensions.json` file, remove the "nrwl.angular-console" extension as the current latest version of the extension doesn't work with devcontainers.
